---
# - name: Clone mainsail repository
#   git:
#     repo: "{{ mainsail_repo }}"
#     dest: "{{ install_dir }}/mainsail"
#     version: "{{ mainsail_version }}"
#     force: yes

# - name: Apply patch hostname
#   patch:
#     src: hostname.patch
#     basedir: "{{ install_dir }}/mainsail"
#     strip: 1

# - name: Install npm dependencies
#   npm:
#     path: "{{ install_dir }}/mainsail"

# - name: Build mainsail
#   command: npm run build
#   args:
#     chdir: "{{ install_dir }}/mainsail"

- name: Create mainsail www folder
  become: true
  file:
    path: "{{ mainsail_www_dir }}"
    state: directory
    owner: "{{ system_user }}"
    group: www-data

# - name: Copy mainsail files to www dir
#   copy:
#     remote_src: yes
#     src: "{{ install_dir }}/mainsail/dist/"
#     dest: "{{ mainsail_www_dir }}"

- name: Copy mainsail files to www dir
  unarchive:
    src: "mainsail.zip"
    dest: "{{ mainsail_www_dir }}"

- name: Copy Mainsail config.json
  template:
    src: config.json.j2
    dest: "{{ mainsail_www_dir }}/config.json"
  notify: restart nginx

- name: Copy nginx common vars for mainsail
  become: true
  template:
    src: nginx_common_vars.conf.j2
    dest: /etc/nginx/conf.d/common_vars.conf

- name: Copy nginx upstreams for mainsail
  become: true
  template:
    src: nginx_upstreams.conf.j2
    dest: /etc/nginx/conf.d/upstreams.conf

- name: Copy nginx config for mainsail
  become: true
  template:
    src: nginx_mainsail.conf.j2
    dest: /etc/nginx/sites-available/mainsail

- name: Remove nginx default site
  become: true
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Link mainsail nginx config to enable sites
  become: true
  file:
    src: /etc/nginx/sites-available/mainsail
    dest: /etc/nginx/sites-enabled/mainsail
    state: link
  notify: restart nginx
