apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mainsail-ingress
spec:
  rules:
  - host: farmlab.lemaker.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: oauth2-proxy
            port:
              number: 4180
